# Numpy (Numerical Python)

In [1]:
# Def: Numpy is a open source python library for Numerical computations.

# Interview Question : What is the difference between python List & numpy array?
# Ans: Ragvender: List are Heterogeneous , while numpy array are homogeneous.
# Numpy array are 50x faster then the List.
# In numpy array elements store in continuous memory location while in list.
# Numpy array are good at multiprocessor

# Numpy is designed C, C++ and Python

In [2]:
# Important operations in Numpy

## 1. Installing, upgrading and importing numpy
## 2. Creating Numpy array's
## 3. Special type of numpy array creation
## 4. Array shape, reshapping and transpose operation
## 5. Size, Datatype and their conversion
## 6. Indexing & Slicing & Modification 
## 7. Mathematical & Statistical operations
## 8. Concatination, Stacking, Splitting of numpy array's

# 1. Installing, upgrading and importing numpy

In [3]:
pip install -U numpy

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: numpy in c:\users\prikshit_ishi\anaconda3\lib\site-packages (1.26.4)
  Using cached numpy-2.3.4-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.4-cp312-cp312-win_amd64.whl (12.8 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4



  You can safely remove it manually.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.18.0 requires ml-dtypes<0.5.0,>=0.4.0, but you have ml-dtypes 0.5.1 which is incompatible.
tensorflow-intel 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.3.4 which is incompatible.
tensorflow-intel 2.18.0 requires tensorboard<2.19,>=2.18, but you have tensorboard 2.19.0 which is incompatible.
autoviz 0.1.905 requires xgboost<1.7,>=0.82, but you have xgboost 3.0.2 which is incompatible.
chromadb 1.0.10 requires fastapi==0.115.9, but you have fastapi 0.104.1 which is incompatible.
chromadb 1.0.10 requires httpx>=0.27.0, but you have httpx 0.25.2 which is incompatible.
chromadb 1.0.10 requires tqdm>=4.65.0, but you have tqdm 4.64.1 which is incompatible.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have num

In [4]:
import numpy as np

In [5]:
np.__version__

'2.3.4'

# 2. Creating Numpy array's

In [6]:
# 1D array

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [7]:
arr = np.array([1,2,3,4,5.5])
print(arr)
print(type(arr))

[1.  2.  3.  4.  5.5]
<class 'numpy.ndarray'>


In [8]:
# data type of elements
arr.dtype

dtype('float64')

In [9]:
arr = np.array([1,2,3,"Hello",5.5])
print(arr)
print(type(arr))
print(arr.dtype)

# U32 means Unicode String data of max 32 length

['1' '2' '3' 'Hello' '5.5']
<class 'numpy.ndarray'>
<U32


In [10]:
# 2D numpy array
arr2 = np.array([['rrr', 'bahuballi', 'OG'],['NTR', 'Prabhas', 'Pavan']])
arr2

array([['rrr', 'bahuballi', 'OG'],
       ['NTR', 'Prabhas', 'Pavan']], dtype='<U9')

In [11]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2.shape

(2, 3)

In [13]:
# 3D numpy array
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [14]:
arr3.ndim

3

In [15]:
arr3.shape

(3, 2, 3)

In [16]:
arr4 = np.array([[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]], [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]])
arr4

array([[[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]],


       [[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]]])

In [17]:
arr4.ndim

4

In [18]:
arr4.shape

(2, 2, 2, 3)

# 3. Special type of numpy array creation

In [19]:
# Array of Zeros 

# 1D Zero numpy array
zero_arr = np.zeros(5)
zero_arr 

array([0., 0., 0., 0., 0.])

In [20]:
# 2D Zero numpy array
zero_arr = np.zeros((2,3))
zero_arr 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# 3D Zero numpy array
zero_arr = np.zeros((3,2,3))
zero_arr 

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# Create and initialize the numpy array with 1 (one)

# 1D Ones numpy array
ones_arr = np.ones(5)
ones_arr 

array([1., 1., 1., 1., 1.])

In [23]:
# 2D Ones numpy array
ones_arr = np.ones((2,3))
ones_arr 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# 3D Ones numpy array
ones_arr = np.ones((2,2,3))
ones_arr 

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [25]:
# filling/initialize the numpy array with specific value

# 1D array with specific value
spe_arr = np.full(5, 6000)
spe_arr

array([6000, 6000, 6000, 6000, 6000])

In [26]:
# 2D array with specific value
spe_arr = np.full((3,2), 60)
spe_arr

array([[60, 60],
       [60, 60],
       [60, 60]])

In [27]:
# 3D array with specific value
spe_arr = np.full((3,2,3), 60)
spe_arr

array([[[60, 60, 60],
        [60, 60, 60]],

       [[60, 60, 60],
        [60, 60, 60]],

       [[60, 60, 60],
        [60, 60, 60]]])

In [30]:
# identity matrix
# identity matrix is a square matrix

identity = np.eye(5)

identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
### random module in numpy

In [35]:
# 1D array of random elements
# rand() function generates uniform distributed values between 0 to 1
np.random.rand(20)

array([0.09912431, 0.44155351, 0.83442854, 0.74559328, 0.04367277,
       0.58434917, 0.18781797, 0.66398859, 0.90970562, 0.19336861,
       0.35872763, 0.60148879, 0.9145339 , 0.43886117, 0.62142354,
       0.66223864, 0.62979199, 0.85098624, 0.24466095, 0.46125571])

In [36]:
# 2D random array with values between 0 to 1 ( uniformly distrubuted)
np.random.rand(2,3)

array([[0.97250224, 0.31765262, 0.54654554],
       [0.14536872, 0.55451578, 0.53891838]])

In [37]:
# 3D matrix
np.random.rand(3,2,3)

array([[[0.94278635, 0.88757181, 0.52784217],
        [0.63001389, 0.85158435, 0.09746003]],

       [[0.8268316 , 0.65737944, 0.16595543],
        [0.06097533, 0.84302249, 0.19738584]],

       [[0.72225292, 0.22430469, 0.08143272],
        [0.55271889, 0.6836529 , 0.3582825 ]]])

In [38]:
# 4D matrix
np.random.rand(3,2,3, 2)

array([[[[0.93637197, 0.89043911],
         [0.53216535, 0.60797262],
         [0.22134827, 0.5242356 ]],

        [[0.69561661, 0.15043699],
         [0.91277747, 0.76256807],
         [0.93526385, 0.794967  ]]],


       [[[0.15938264, 0.70655597],
         [0.14061355, 0.56318838],
         [0.09158544, 0.60670958]],

        [[0.6159754 , 0.21088185],
         [0.18279501, 0.28313411],
         [0.01222357, 0.71915862]]],


       [[[0.5046201 , 0.75138166],
         [0.87687295, 0.79850124],
         [0.83637059, 0.81467465]],

        [[0.03014812, 0.66378096],
         [0.93922809, 0.45250725],
         [0.29735452, 0.91117433]]]])

In [39]:
# random() function 

np.random.random(5)

array([0.21193842, 0.90927143, 0.53467472, 0.28124361, 0.65394852])

In [41]:
np.random.random((2,3))

array([[0.37974374, 0.4963749 , 0.59787   ],
       [0.75989231, 0.66560727, 0.64277314]])

In [42]:
np.random.random((2,3,2))

array([[[0.20373927, 0.96858639],
        [0.19489501, 0.44578886],
        [0.18639982, 0.72924927]],

       [[0.78184352, 0.39680602],
        [0.72064313, 0.05205066],
        [0.885587  , 0.60896279]]])

In [45]:
# randn() : This will generate most of the random values between -3 to +3
# randn() function generates values as Standard normal distribution ( mean = 0, std = 1)

# 1D array
np.random.randn(50)

array([ 0.28292207, -0.61352135, -0.51744405, -0.80713287,  1.04205338,
       -0.12644926,  0.404975  ,  0.05009201, -1.78834917,  0.21517739,
        0.21764039, -1.45742213,  0.93580635, -1.2634637 ,  1.54039553,
       -1.16573283, -0.52807643, -1.10333998,  1.06227625,  0.58481405,
        0.43031315, -0.70324935,  1.67335137,  0.10255514,  0.7889101 ,
        0.65346484, -0.14983422, -0.31392888,  1.29850888, -0.64587061,
        0.79291376,  0.16706739, -0.84140317, -2.5292811 , -1.34515135,
        0.24812428, -0.66572453, -1.06640865, -0.59428748,  0.80836961,
        0.33384304, -1.00103261,  0.56143637, -0.32848441, -0.17698448,
       -0.09180588, -0.69421883, -1.50799651, -0.27893211, -0.86964952])

In [46]:
np.random.randn(2,3)

array([[-0.69776013,  1.11476452, -1.55024352],
       [ 0.41296281,  1.39609775, -0.24561582]])

In [47]:
np.random.randn(2,3,2)

array([[[-0.78251343, -0.94027868],
        [ 0.70008815,  0.08123292],
        [-2.33276123, -0.24261515]],

       [[-1.88567492,  0.3857949 ],
        [ 0.81165448, -0.61064962],
        [-0.99112153, -0.02212017]]])

In [56]:
# randint() : generating interger values in a fix range

rand_int_data = np.random.randint(10, 1000, 8)  # 10 inclusive, 100 exclusive
rand_int_data

array([436, 360, 586, 243, 759, 181,  94, 765], dtype=int32)

In [57]:
rand_int_data = np.random.randint(10, 1000, (2,3))  # 10 inclusive, 100 exclusive
rand_int_data

array([[512, 645, 364],
       [925, 822, 399]], dtype=int32)

In [63]:
rand_int_data = np.random.randint(10, 1000, (2,3,2))  # 10 inclusive, 100 exclusive
rand_int_data

array([[[521, 193],
        [660, 787],
        [753, 738]],

       [[629, 443],
        [393,  63],
        [794, 558]]], dtype=int32)

In [79]:
# choice() : This is used for selecting categorical data

GF = np.array(['Turky', 'Murgi', 'Chuhiya', 'Bakri'])

np.random.choice(GF, size = 3)

array(['Turky', 'Chuhiya', 'Turky'], dtype='<U7')

In [72]:
np.random.choice(GF, size = 3, replace = False)

array(['Chuhiya', 'Murgi', 'Turky'], dtype='<U7')

In [76]:
np.random.choice(GF, size = 10, p = [0.4, 0.3, 0.2, 0.1])

array(['Turky', 'Turky', 'Murgi', 'Chuhiya', 'Chuhiya', 'Chuhiya',
       'Turky', 'Murgi', 'Chuhiya', 'Turky'], dtype='<U7')

In [115]:
# Pramod is very faithfull
np.random.seed(42)
np.random.choice(GF, size = 3)

ValueError: Seed must be between 0 and 2**32 - 1

In [90]:
### create sequences, shuffled, linearly spaced array

In [112]:
arr1 = np.arange(1,10, 2)  # 1 is inclusive , 10 is excludid
arr1

array([1, 3, 5, 7, 9])

In [100]:
# shuffle modify the orignal array
np.random.shuffle(arr1)
arr1

array([7, 9, 4, 8, 2, 1, 6, 3, 5])

In [106]:
# permutation don't modify the orignal array
arr2 = np.random.permutation(arr1)
arr2

array([3, 9, 5, 2, 1, 4, 7, 6, 8])

In [113]:
# Generate linear spaced numbers between 1 to 10

arr3 = np.linspace(1,10,40)  # linspace(start, end, size)
arr3

array([ 1.        ,  1.23076923,  1.46153846,  1.69230769,  1.92307692,
        2.15384615,  2.38461538,  2.61538462,  2.84615385,  3.07692308,
        3.30769231,  3.53846154,  3.76923077,  4.        ,  4.23076923,
        4.46153846,  4.69230769,  4.92307692,  5.15384615,  5.38461538,
        5.61538462,  5.84615385,  6.07692308,  6.30769231,  6.53846154,
        6.76923077,  7.        ,  7.23076923,  7.46153846,  7.69230769,
        7.92307692,  8.15384615,  8.38461538,  8.61538462,  8.84615385,
        9.07692308,  9.30769231,  9.53846154,  9.76923077, 10.        ])

# 4. Array shape, reshapping and transpose operation

In [3]:
# shape() : used to check the dimension of the numpy array
import numpy as np
cloth_arr = np.array([['Shirt & dhoti', 'Angvastra' , 'Panche'], ['Half Saree', 'Lehenga' , 'Silk Saree']])

print(cloth_arr)
print(cloth_arr.shape)

[['Shirt & dhoti' 'Angvastra' 'Panche']
 ['Half Saree' 'Lehenga' 'Silk Saree']]
(2, 3)


In [4]:
# reshape()

print(cloth_arr.reshape(3,2))

[['Shirt & dhoti' 'Angvastra']
 ['Panche' 'Half Saree']
 ['Lehenga' 'Silk Saree']]


In [5]:
print(cloth_arr.reshape(1,6))

[['Shirt & dhoti' 'Angvastra' 'Panche' 'Half Saree' 'Lehenga'
  'Silk Saree']]


In [6]:
print(cloth_arr.reshape(6,1))

[['Shirt & dhoti']
 ['Angvastra']
 ['Panche']
 ['Half Saree']
 ['Lehenga']
 ['Silk Saree']]


In [8]:
# print(cloth_arr.reshape(4,2))   # ERROR

ValueError: cannot reshape array of size 6 into shape (4,2)

In [10]:
print(cloth_arr.reshape(1,2,3))

[[['Shirt & dhoti' 'Angvastra' 'Panche']
  ['Half Saree' 'Lehenga' 'Silk Saree']]]


In [11]:
print(cloth_arr.reshape(6))

['Shirt & dhoti' 'Angvastra' 'Panche' 'Half Saree' 'Lehenga' 'Silk Saree']


In [12]:
# ravel() : flatten any array to 1D array

oneD_arr = cloth_arr.ravel()
print(oneD_arr)

['Shirt & dhoti' 'Angvastra' 'Panche' 'Half Saree' 'Lehenga' 'Silk Saree']


In [13]:
cloth_arr

array([['Shirt & dhoti', 'Angvastra', 'Panche'],
       ['Half Saree', 'Lehenga', 'Silk Saree']], dtype='<U13')

In [14]:
# transpose of a matrix : row become column and columns becomes rows

print(cloth_arr.T)

[['Shirt & dhoti' 'Half Saree']
 ['Angvastra' 'Lehenga']
 ['Panche' 'Silk Saree']]


In [15]:
# create a nD array quickly

# 5D array
nD_arr = np.arange(1,49).reshape(2, 2, 3, 2, 2)
nD_arr

array([[[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]],

         [[ 9, 10],
          [11, 12]]],


        [[[13, 14],
          [15, 16]],

         [[17, 18],
          [19, 20]],

         [[21, 22],
          [23, 24]]]],



       [[[[25, 26],
          [27, 28]],

         [[29, 30],
          [31, 32]],

         [[33, 34],
          [35, 36]]],


        [[[37, 38],
          [39, 40]],

         [[41, 42],
          [43, 44]],

         [[45, 46],
          [47, 48]]]]])

# 5. Size, Data Type and Conversion

In [20]:
# size : use to find the number of elements in the numpy array

songs = np.array(['Kissik' ,'Monica', 'Manohari Manohari'])

print(songs.size)
print(cloth_arr.size)
print(nD_arr.size)

3
6
48


In [21]:
# U : Unicode string with max 8 length
print(songs.dtype)

<U17


In [22]:
# astype() : for data type conversion

song_duration = np.array([4.32, 5.2, 12.5])

int_arr = song_duration.astype(int)
int_arr

array([ 4,  5, 12])

In [26]:
song_earning = np.array(["40", "500" , "1000"])
int_arr = song_earning.astype(int)
print(int_arr)

[  40  500 1000]


In [28]:
song_earning = np.array(["40.5", "500.6" , "1000"])
float_arr = song_earning.astype(float)
print(float_arr)

[  40.5  500.6 1000. ]


In [33]:
song_earning = np.array([40, 500.5 , "600"])
#int_arr = song_earning.astype(int)
# print(int_arr)
print(song_earning.dtype)

<U32


In [34]:
np.array([True, False, True]).astype(int)

array([1, 0, 1])

In [35]:
np.array([0, 2, 5, -1]).astype(bool)

array([False,  True,  True,  True])

# 6. Indexing, Slicing and Modification

In [36]:
sweets = np.array([['Pootharekulu', 'Jangiri', 'Coconut laddo'], 
                   ['Kaju katli', 'Rava ladoo', 'Modakam']])

print(sweets[1,2])

Modakam


In [37]:
print(sweets[0, :])

['Pootharekulu' 'Jangiri' 'Coconut laddo']


In [38]:
print(sweets[: , 1])

['Jangiri' 'Rava ladoo']


In [40]:
print(sweets[-1, -2])

Rava ladoo


In [41]:
print(sweets[-1])

['Kaju katli' 'Rava ladoo' 'Modakam']


In [42]:
sweets[1,1] = 'Payasam'

In [43]:
sweets

array([['Pootharekulu', 'Jangiri', 'Coconut laddo'],
       ['Kaju katli', 'Payasam', 'Modakam']], dtype='<U13')

# 7. Mathematical & Statistical operations

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr + 10)

[[11 12 13]
 [14 15 16]]


In [4]:
print(arr - 10)

[[-9 -8 -7]
 [-6 -5 -4]]


In [5]:
print(arr * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [6]:
print(arr ** 2)

[[ 1  4  9]
 [16 25 36]]


In [7]:
age = np.array([20, 22, 21, 23, 21, 21, 22, 16, 18, 22, 80, 90, 120, 200])

print(np.sum(age))

696


In [8]:
print(np.min(age))

16


In [9]:
print(np.max(age))

200


In [10]:
print(np.mean(age))

49.714285714285715


In [11]:
print(np.var(age))

2755.918367346939


In [12]:
print(np.std(age))

52.496841498769605


In [13]:
print(np.percentile(age, 50))

22.0


In [14]:
print(np.quantile(age, 0.50))

22.0


In [16]:
# argmin() : finding the index of minimum element
age = np.array([20, 22, 21, 23, 21, 21, 22, 16, 18, 22, 80, 90, 120, 200])

print(np.argmin(age))

7


In [17]:
# argmax() : finding the index of maximum element

print(np.argmax(age))

13


In [21]:
# log() : finding the log value. 

# log1000 (base = 10) = 3

print(np.log10(1000))
print(np.log2(1024))
print(np.log(1000))  # base = e = 2.71

3.0
10.0
6.907755278982137


In [23]:
print(np.sqrt(900))

30.0


In [25]:
pi = 3.1415645

print(np.round(pi, 2))

3.14


In [26]:
print(np.floor(pi))

3.0


In [27]:
print(np.ceil(pi))

4.0


In [28]:
print(np.abs(-456))

456


In [30]:
# sorting of numpy array
fruits = np.array(['Arati Pandu', 'Mammadi Pandu', 'Naarinja', 'Kobbari Kaaya'])

In [31]:
print(np.sort(fruits))

['Arati Pandu' 'Kobbari Kaaya' 'Mammadi Pandu' 'Naarinja']


In [32]:
fruits_price = np.array([80, 100, 60, 40])

print(np.sort(fruits_price))

[ 40  60  80 100]


In [33]:
# interview Question : output?

print(np.sort(fruits_price)[::-1])

[100  80  60  40]


In [36]:
# 2D array sorting 

arr2 = np.array([[10, 5, 56], [9, 60, 75]])
np.sort(arr2)

array([[ 5, 10, 56],
       [ 9, 60, 75]])

# 8. Concatination, Stacking, Splitting of Numpy array

In [37]:
# concatenate() : This will merge the two or more numpy arrays into one array

# 1D array concatenation
arr1 = np.array([100, 200, 1000])  # pocket money
arr2 = np.array([0, -5, 20]) # remaining pocket money

arr = np.concatenate((arr1, arr2))
print(arr)

[ 100  200 1000    0   -5   20]


In [38]:
# 2D arrays concatenate

# axis = 1: Horozontal concatenation ( column wise)

arr1 = np.array([[50, 20, 2],
                 [5, 8, 9]])

arr2 = np.array([[500, 2000, 200],
                 [100, 800, 900]])

arr_2D = np.concatenate((arr1, arr2), axis = 1)
print(arr_2D)

[[  50   20    2  500 2000  200]
 [   5    8    9  100  800  900]]


In [39]:
# 2D arrays concatenate

# axis = 0: Vertical concatenation ( row-wise)

arr1 = np.array([[50, 20, 2],
                 [5, 8, 9]])

arr2 = np.array([[500, 2000, 200],
                 [100, 800, 900]])

arr_2D = np.concatenate((arr1, arr2), axis = 0)
print(arr_2D)

[[  50   20    2]
 [   5    8    9]
 [ 500 2000  200]
 [ 100  800  900]]


In [42]:
# Interview Question : output of below code?

# IMP Point: We cannot concatenate() two different dimension arrays

a = np.array([1,2,3])
b = np.array([[4,5,6]])

np.concatenate((a,b), axis = 0)  # either put axis = 1

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [46]:
# Interview Question : output of below code?

# IMP Point: We can concatenate below arrays row wise

a = np.array([[1,2,3],
              [4,5,6]])  # 2,3
b = np.array([[7,8,9]])  # 1, 3

np.concatenate((a,b), axis = 0) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
# Interview Question : output of below code?

# IMP Point: We cannot concatenate below arrays column wise

a = np.array([[1,2,3],
              [4,5,6]])  # 2,3
b = np.array([[7,8,9]])  # 1, 3

np.concatenate((a,b), axis = 1) 

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

### stack() function in numpy

In [47]:
# Def : Stack() function is also used for merging the numpy arrays.
# Stack() function will add one more extra dimension in final output array

In [48]:
arr1 = np.array([100, 200, 1000])  # pocket money
arr2 = np.array([0, -5, 20]) # remaining pocket money

# axis = 0:  Row-wise stacking

stacked_arr = np.stack((arr1, arr2), axis = 0)
print(stacked_arr)

[[ 100  200 1000]
 [   0   -5   20]]


In [50]:
print(np.concatenate((arr1,arr2)))

[ 100  200 1000    0   -5   20]


In [51]:
# axis = 1 : Column wise stacking

stacked_arr = np.stack((arr1, arr2), axis = 1)
print(stacked_arr)
print(stacked_arr.shape)

# n : nmber of input array
# axis = 0 : N, a1,a2......ak
# axis = 1 : N,   

[[ 100    0]
 [ 200   -5]
 [1000   20]]


In [52]:
# 2D array stacking

# axis = 0: row-wise

arr1 = np.array([[50, 20, 2],
                 [5, 8, 9]])

arr2 = np.array([[500, 2000, 200],
                 [100, 800, 900]])

stacked_2D = np.stack((arr1, arr2), axis = 0)
print(stacked_2D)

[[[  50   20    2]
  [   5    8    9]]

 [[ 500 2000  200]
  [ 100  800  900]]]


In [53]:
# axis = 1 : column wise

rr1 = np.array([[50, 20, 2], [5, 8, 9]])

arr2 = np.array([[500, 2000, 200], [100, 800, 900]])

stacked_2D = np.stack((arr1, arr2), axis = 1)
print(stacked_2D)

[[[  50   20    2]
  [ 500 2000  200]]

 [[   5    8    9]
  [ 100  800  900]]]


In [ ]:
# Interview Question

a  = np.array([1,2,3])
b = np.array([[4,5,6]])

np.stack((a,b), axis = 0)

In [2]:
# Interview Question
a  = np.array([1,2,3])
b = np.array([[4,5,6]])

np.stack((a,b), axis = 1)

ValueError: all input arrays must have the same shape

In [1]:
import numpy as np

In [3]:
 ## vstack() : vartical stacking
# vstack() is same as vartical concatination

arr1 = np.array([[50, 20, 2], [5, 8, 9]])

arr2 = np.array([[500, 2000, 200], [100, 800, 900]])
result = np.vstack((arr1, arr2))
print(result)

[[  50   20    2]
 [   5    8    9]
 [ 500 2000  200]
 [ 100  800  900]]


In [5]:
np.concatenate((arr1, arr2))

array([[  50,   20,    2],
       [   5,    8,    9],
       [ 500, 2000,  200],
       [ 100,  800,  900]])

In [6]:
 ## hstack() : horizontal stacking
# hstack() is same as horizontal concatination

arr1 = np.array([[50, 20, 2], [5, 8, 9]])

arr2 = np.array([[500, 2000, 200], [100, 800, 900]])
result = np.hstack((arr1, arr2))
print(result)

[[  50   20    2  500 2000  200]
 [   5    8    9  100  800  900]]


In [14]:
np.concatenate((arr1, arr2), axis = 1)

array([[  50,   20,    2,  500, 2000,  200],
       [   5,    8,    9,  100,  800,  900]])

# splitting numpy arrays

In [22]:
# split() : used for splitting the big array to small array
slipper_speed_mom_arr = np.array([10,20,30,100,35,60,25,45,55])
split_arr = np.split(slipper_speed_mom_arr,3)
split_arr

[array([10, 20, 30]), array([100,  35,  60]), array([25, 45, 55])]

In [24]:
print(split_arr[0])
print(split_arr[1])
print(split_arr[2])

[10 20 30]
[100  35  60]
[25 45 55]


In [25]:
print(split_arr[0][0])

10


In [30]:
# split() : used for splitting the big array to small array
slipper_speed_mom_arr = np.array([[10,20], [30,100], [35,60]])
split_arr = np.split(slipper_speed_mom_arr,3)
split_arr

[array([[10, 20]]), array([[ 30, 100]]), array([[35, 60]])]

In [31]:
print(split_arr[0])


[[10 20]]


In [38]:
print(split_arr[0][0][0])

10
